GET http://localhost:5118/health


###
GET http://localhost:5118/games

### Get by id
GET http://localhost:5118/games/1

###
POST  http://localhost:5118/games
Content-Type: application/json

{
   "name" : "God of war",
   "genre" : "Sports",
    "price" : 4.99,
    "releaseDate" : "2020-12-24"
}

###
PUT  http://localhost:5118/games/1
Content-Type: application/json

{
   "name" : "God of war",
   "genre" : "Sports",
    "price" : 4.99,
    "releaseDate" : "2020-12-24"
}
###
DELETE  http://localhost:5118/games/1


